### ISSUE TITLE
[BUG] processing demo activity's does not complete

### ISSUE THREAD

**Issue by gotiniens** [fgebhart/workoutizer#160] opened 2021-06-16 19:51 UTC
**Describe the bug**
When using the `run_docker.sh` script, and initializing the database I get an timeout error. SOmtetimes it seems to be doing nothing, and after pushing `ctrl+c ` it show the timeout error.

**To Reproduce**
1. run the `run_docker.sh` script
2. `wkz init --demo`
3. see error:
```06-16 21:31:40 - DEBUG - wkz.file_importer - finished parsing file /workspaces/workoutizer/tracks/2020-10-25-10-54-06.fit.
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.8/site-packages/distributed/comm/core.py", line 285, in connect
    comm = await asyncio.wait_for(
  File "/usr/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/venv/bin/wkz", line 33, in <module>
    sys.exit(load_entry_point('workoutizer', 'console_scripts', 'wkz')())
  File "/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/workspaces/workoutizer/workoutizer/cli.py", line 40, in init
    _init(import_demo_activities=demo)
  File "/workspaces/workoutizer/workoutizer/cli.py", line 163, in _init
    run_importer__dask(models, importing_demo_data=True)
  File "/workspaces/workoutizer/wkz/file_importer.py", line 389, in run_importer__dask
    sse.send(msg, "blue", "DEBUG")
  File "/tmp/venv/lib/python3.8/site-packages/distributed/deploy/spec.py", line 454, in __exit__
    super().__exit__(typ, value, traceback)
  File "/tmp/venv/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 419, in __exit__
    return self.sync(self.__aexit__, typ, value, traceback)
  File "/tmp/venv/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 192, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/tmp/venv/lib/python3.8/site-packages/distributed/utils.py", line 354, in sync
    raise exc.with_traceback(tb)
  File "/tmp/venv/lib/python3.8/site-packages/distributed/utils.py", line 337, in f
    result[0] = yield future
  File "/tmp/venv/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/tmp/venv/lib/python3.8/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/tmp/venv/lib/python3.8/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/tmp/venv/lib/python3.8/site-packages/distributed/deploy/cluster.py", line 428, in __aexit__
    await f
  File "/tmp/venv/lib/python3.8/site-packages/distributed/deploy/spec.py", line 426, in _close
    await self._correct_state()
  File "/tmp/venv/lib/python3.8/site-packages/distributed/deploy/spec.py", line 341, in _correct_state_internal
    await self.scheduler_comm.retire_workers(workers=list(to_close))
  File "/tmp/venv/lib/python3.8/site-packages/distributed/core.py", line 791, in send_recv_from_rpc
    comm = await self.live_comm()
  File "/tmp/venv/lib/python3.8/site-packages/distributed/core.py", line 749, in live_comm
    comm = await connect(
  File "/tmp/venv/lib/python3.8/site-packages/distributed/comm/core.py", line 309, in connect
    raise IOError(
OSError: Timed out trying to connect to inproc://10.1.0.2/13/1 after 10 s
```

**Additional context**
It also happens when running the tests with `pytest tests/db_tests/test_cli.py, if I edit the tests file and remove the import tests all works well.

**Comment by fgebhart** [comment] 2021-06-17 15:22
Thanks for filing this issue @gotiniens 

It is a bit strange that I don't see these kind of issues running the Docker container using VSCode...

Anyways, I was able to reproduce it. At first it kept hanging forever. Interrupting (and deleting the `db.sqlite3` file) and rerunning it again caused the described `OSError: Timed out trying to connect to` error you reported.

Currently I suspect the "server sent event (sse)" to be the root cause. It is the last call to the workoutizer source code within the given traceback
```
File "/workspaces/workoutizer/wkz/file_importer.py", line 389, in run_importer__dask
    sse.send(msg, "blue", "DEBUG")
```
It would also kind of make sense, since there is no server running to receive the message within the context of `wkz init`.

I will try to investigate this further and see if I can find a fix.

**Comment by fgebhart** [comment] 2021-06-17 20:39
I figured it has nothing to do with sse but rather with the threads of the dask cluster. The linked PR changes how the cluster is set up, which seemed to solve the problem. (The PR includes also a bunch of other things, which I was working on the other day)

However, the issue occurs only sometimes and is not fully deterministic, so it would be great if you could also checkout to the branch of the PR and verify that the issue is gone.

**Comment by gotiniens** [comment] 2021-06-17 21:15
This is a lot better, I've run `wkz init --demo` and `pytest tests/db_tests/test_cli.py` multiple times, and had only 1 time the Time out error. I will test a but further tomorrow.

**Comment by fgebhart** [comment] 2021-06-18 19:38
I hoped it would fix the issue completely 🤷‍♂️ Anyway, I will also try to run some more tests on this.

**Comment by gotiniens** [comment] 2021-06-19 11:33
I was able to do some more testing and I think I have a hypothesis. Concurrency is causing an issue, Every time I run the tests with `pytest tests/db_tests/test_cli.py` all tests succeed. When I run the tests with `pytest tests/db_tests/test_cli.py -n4` the results are not consistent. But most times I get the following error:
```
  /tmp/venv/lib/python3.8/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
  Perhaps you already have a cluster running?
  Hosting the HTTP server on port 44083 instead
    warnings.warn(
```
This sounds like there is already on wkz instance running for one of the other currently running tests, this could also expplain the time out errors. Those can occur when a test is usning an wkz instance from another test which just finished and thus clean up all remaining processes.

I would say this should also happen on the ci pipelines and your VScode docker setup. Which seems to not be the case, weird.

**Comment by fgebhart** [comment] 2021-06-19 12:19
Thanks for digging into this!

> But most times I get the following error:
> 
> ```
>   /tmp/venv/lib/python3.8/site-packages/distributed/node.py:160: UserWarning: Port 8787 is already in use.
>   Perhaps you already have a cluster running?
>   Hosting the HTTP server on port 44083 instead
>     warnings.warn(
> ```

This is just a warning not an error. It originates from dask distributed and simply complains about node already running on the default port, but it does not fail. Instead it simply runs the new node on another port. I am aware of these warnings but don't think these are the root cause.

The situation is similar to what you described:
* Each test requiring a dask cluster will spin one up
* if there is a cluster already running at the given port, this warning is raised
* however, each test will have its cluster available as long as it needs it

I also get these kind of warnings in VSCode and they are present in CI (check the ["Run Tests" dropdown](https://github.com/fgebhart/workoutizer/runs/2833248738?check_suite_focus=true)). But I didn't get the timeout error (yet).

There is also an open [issue](https://github.com/dask/distributed/issues/4806) at dask distributed on the exact same topic. People there seem also to be working on it, so we might be lucky to get this fixed soonish.

That's why I'm quite confident that this warning is not the cause of of all evil. It could, however, still be concurrency in general...

**Comment by fgebhart** [comment] 2021-06-21 19:16
The linked PR reduces the number of workers to 1. I conducted a series of tests (about 20) and did not get the mentioned timeout error at all. Thus I would consider this issue fixed  and close it for now. Feel free to re-open again in case this does not fix the issue for you.

A bit of context on the dask distributed setup:
Initially I introduced dask to speed up the file parsing process. I currently have about 500 activity files, reimporting these sequentially takes for ever. Recently I realized that not only the parsing takes quite some time but also the "saving to database" step. For the sake of simplicity I prefer to stick with sqlite, which, however, allows sequential write access to the db only. Because of this I implemented an approach which parses the files in parallel and writes the results to the db sequentially, using `as_completed` from `dask.distributed`. (Using a lock or a semaphore would be a similar approach)
Reducing the number of workers to 1 means that there is only one worker parsing the files one after another and one scheduler which will receive the parsed results and save them to the database. A setup with 2 workers would quickly lead to the process of saving the files to db being the bottleneck. Therefore, a setup of 1 worker and 1 scheduler is only a little slower than a setup with 2 workers.
I will keep an eye on this topic and probably try to improve it further.

**Closed** 2021-06-21 19:17 UTC
Labels: bug
